### ISSUE TITLE
Please add Linux support

### ISSUE THREAD

**Issue by BohdanOpyr** [thegoodhen/AprilTools#1]

**Comment by thegoodhen** [comment]
I'm on it.

**Comment by ronsn** [comment]
> I'm on it.

Awesome! =)

**Comment by thegoodhen** [comment]
I have succesfully managed to compile and run the software under Linux now. I will update the repository tomorrow.

**Comment by thegoodhen** [comment]
Uh... I managed to get it work on my new Linux machine, but not on my old one... So now I am downloading a virtualbox image of a Linux version which is old, but not insanely old to see if it will compile and work there. Then hopefully I can add the binaries here.

**Comment by Deerdevil** [comment]
Great work on this! Will there be support for the macs in the future? :)

**Comment by thegoodhen** [comment]
Ehm ehm.
Now it's not the right time to ask that.
I've just spent around 5 hours unsuccessfully trying to port it to Linux. :D 
But hopefully I am close now. I am still really new to this. 

But in all seriousness, thanks, and I hope there will be! But I don't really have a mac, so it will be a bit difficult.

**Comment by Deerdevil** [comment]
Yeah dont sweat it, just be proud of what you already have accomplished! Ill fire up the old pc and use that for the tracking part :)

**Comment by thegoodhen** [comment]
Thanks! It should be trivial to port it, since it's pretty much a Linux code. I am having trouble with libc versions, opencv versions and more fun stuff.

**Comment by thegoodhen** [comment]
I managed to compile it, but it seems like the Linux repositories have vastly different versions of opencv with vastly different APIs. So I will need to bundle openCV with it somehow. Tried linking it statically, but that failed, tried including the libraries, but they were dependant on a very new version of libc... Now I am trying to compile opencv from source to get the libraries dependent on an older versions of libc for better compatibility... Then I'll try to either link it statically or somehow dynamically while still including the libraries in the .zip .

**Comment by f0x52** [comment]
I got it working on Arch by installing the `opencv` package, installing `apriltag` from source and then running
`gcc AprilTools.cc -o AprilTools $(pkg-config --cflags --libs opencv4) -I/usr/local/include/apriltag -L/usr/local/lib -lapriltag -lstdc++ -lm -Wl,-rpath /usr/local/lib`

**Comment by thegoodhen** [comment]
@f0x52  Me too. I got this working on Kali and Ubuntu using (more or less) the approach you describe. But I CAN'T for the love of God manage to compile in a way that would allow me to distribute the whole thing without forcing the user to install opencv. 

I can't manage to link opencv statically. Do you have any idea how to do it?

**Comment by christoph1703** [comment]
Maybe an install script/makefile is the way to go? At least that's what [gocv](https://github.com/hybridgroup/gocv#ubuntulinux) uses and it works very well every time and on different systems. I'm not sure how difficult it is to implement.
Personally, I don't mind dynamic libraries as long as I don't have to find and install everything manually.

**Comment by thegoodhen** [comment]
@christoph1703 The thing is that the code is dependant on a newer version of OpenCV than the one that can be obtained by apt-get on some relatively new-ish Linux distros, such as Ubuntu 16.04 . 

This would force the users to compile openCV from source, which I tried on a virtual machine I literally had to leave it overnight to even complete.

I guess I could use an install script, which would copy the dynamic libraries to where they belong. I will take a look at gocv. Thank you for the comment!

**Comment by thegoodhen** [comment]
Hmmm actually I can take the opencv compilation/installation makefile I found somewhere and then just edit it to install the prebuilt libraries. Yea, probably the best way. I'll try it soon.

**Comment by BohdanOpyr** [comment]
Good luck, I hope everything will work! Makefile is in my opinion the best way to go!

**Comment by HansH** [comment]
I've opened pullrequest #9, which adds a cmake file, and instructions on how to build on Ubuntu and MacOS. This will not solve your problems with older linux versions, though

**Comment by thegoodhen** [comment]
> I've opened pullrequest #9, which adds a cmake file, and instructions on how to build on Ubuntu and MacOS. This will not solve your problems with older linux versions, though

@HansH Wait, so it is now working under MacOS? AMAZING!

I just got it working on Ubuntu 16-19 without the need for installation. Updating everything shortly.

**Comment by thegoodhen** [comment]
@HansH Thank you for your amazing work. I've merged your pull request. I have added a Linux binary release now. I have successfully tested this release on Ubuntu 16.04, 18.04 and 19.04. Closing the issue as solved.
