### ISSUE TITLE
Blender can't proccess / load the track.txt data

### ISSUE THREAD

**Issue by mteillet** [thegoodhen/AprilTools#11]
Hello, I tried on other blender builds as well.
Either Blender refuses to activate the plugin addon when I click on the tickbox / or it stops when I load the track.txt file, returning this message : 

![Capture](https://user-images.githubusercontent.com/54497763/66119561-27ce3480-e5d9-11e9-863f-57bf27a84bbd.JPG)

**Comment by thegoodhen** [comment]
Hi, are you the "starblasters8" from the comment on my youtube video? I don't know that this problem is related to. I will look into it soon.

**Comment by thegoodhen** [comment]
Ok, I think they changed the API in the latest Blender build? I will try to replicate the error and then try to fix it.

**Comment by mteillet** [comment]
Hello,
No, I am not starblasters8, he might have stumbled on the same issue as me. Thank you very much

**Comment by thegoodhen** [comment]
@mteillet try downloading the import script again. I hope it's fixed.

**Comment by mteillet** [comment]
Works great, thank you !
