### ISSUE TITLE
Cannot import tracking file

### ISSUE THREAD

**Issue by AndrOS101RU** [thegoodhen/AprilTools#17]
When I was trying to import a file, a got this error:
RuntimeError: Error: Cannot read 'first line of tracking data'. No such file or directory.
I'm using blender 2.80

**Comment by LeFlawk** [comment]
Can confirm that this also happens with Blender 2.81.
Using the [previous version](https://github.com/thegoodhen/AprilTools/commit/eef6754e39edfc07e9b7d1e2bbb9bea1150eec5f) works fine though

**Comment by thegoodhen** [comment]
Unable to replicate on Blender 2.901 and Blender 2.91. Assuming it's a Blender issue. Closing. Feel free to reopen if problem persists.
