### ISSUE TITLE
Missing apriltag.h

### ISSUE THREAD

**Issue by olekolek1000** [thegoodhen/AprilTools#2]
First of all, I'd like to thank you for such a great library. 
I would like to compile this myself (for Linux), but I don't see these files anywhere:
apriltag.h
tag36h11.h
tag25h9.h
tag16h5.h
tagCircle21h7.h
tagCircle49h12.h
tagCustom48h12.h
tagStandard41h12.h
tagStandard52h13.h
common/getopt.h
common/image_u8.h
common/image_u8x4.h
common/pjpeg.h
common/zarray.h
common/g2d.h
apriltag_pose.h

**Comment by f0x52** [comment]
I think basically all of those come from the apriltag library, https://github.com/AprilRobotics/apriltag
Please keep me posted on how compilation for Linux goes :D

**Comment by thegoodhen** [comment]
Hello! Thank you! So far, it's not much... I was just playing around with the April Tags during my robotics  classes and got this idea, so I put something together real quick for people to enjoy. But I do plan to continue the development! And yes, f0x52 is right.

I compiled it on windows under cygwin as:

g++ -o apriltags.exe apriltag_demo.cc -I.. -L .. -llibapriltag `pkg-config opencv --cflags --libs`

For this, I needed the apriltags.so file together with the .h files in the outer directory (./../). 

The .so file appeared when I ran cmake, as described in: https://github.com/AprilRobotics/apriltag

**Comment by piotao** [comment]
I was able to compile it, but I was not able to link it. Here is the command I've used:

gcc -c AprilTools.cc -o AprilTools.o -I apriltag/ -L apriltag/ -L apriltag/lib -llibapriltag `pkg-config opencv --cflags --libs`

My configuration is that I have apriltag lib INSIDE AprilTools, and it is compiled inside too, so I have apriltag/lib dir with libapriltag.so.3.1.0 inside. However, linker do not see the option -llibapriltag, even when I put -L apriltag/lib into command. Strange.

**Comment by thegoodhen** [comment]
@piotao Thank you, you have helped me figure out how to compile the whole thing under Linux. The binaries are now released. The steps necessary to compile the program for source have been kindly described in the readme by @HansH in #1 .  Closing the issue as solved.
