### ISSUE TITLE
Tag is not aligned with marker on vertical video

### ISSUE THREAD

**Issue by misaalanshori** [thegoodhen/AprilTools#29]
Here is one of the frame:
![image](https://user-images.githubusercontent.com/38964181/84720068-3d3c9080-afa7-11ea-81b5-c3bcba1903ec.png)

The video was recorded vertically at 4k and rotated 90° on Adobe Premiere and exported as 2160x3840 PNG. I don't remember seeing any errors during the tracking process, but maybe I just didn't notice it.

I'm not really sure how to get everything to be aligned/tracked properly, I tried moving stuff around but I couldn't get it to be correctly aligned

**Comment by misaalanshori** [comment]
Just want to add an update, I recorded a version horizontally and everything looked correct, the tag was aligned and tracked correctly, the estimated focal length was accurate, but after rendering ~600 frames I stopped it and decided to check the result and unfortunately the object was not locked in place properly... I know I made sure that the tag/marker was aligned with the bottom of the object.
Not sure where I messed up, but if someone could help it would be great... 
Here is the rendered result:
https://www.youtube.com/watch?v=pbmKwuctckg

**Comment by thegoodhen** [comment]
Hello, did you fix it, or is it still a problem?

**Comment by misaalanshori** [comment]
I haven't tested it again, but after closing this issue I just kinda gave up and recorded it horizontally and cropped it vertically before posting the video. 
When the tracking data is imported to blender, the background video was stretched, so I changed the resolution to the correct resolution and aspect ratio. My guess is that when changing the resolution in blender, I also need to realign the marker or the camera to be correctly aligned again, but I'm not sure how to realign everything back. 

I also don't have the files for the project that I took that screenshot in, and it's been a while since I opened this issue so I have forgotten most of the details. you could try duplicating this issue if you want, I think what I did was just process 9:16 images, import the data to blender, and then corrected the resolution in blender.

**Comment by thegoodhen** [comment]
I really need to get back to this project, I've been meaning to do it for MONTHS now, but new things keep coming up. It really sucks. I'll try looking into it some day hopefully. ;-;
