### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [thegoodhen/AprilTools#3]
There is no LICENSE or COPYING file for this project. The default is copyright.

You should license this project under the AGPL3 or GPL3 license. Directions on how to apply the license are at the bottom of the license file under the `How to Apply These Terms to Your New Programs` heading.  There is a helpful guide for the GPL at https://www.gnu.org/licenses/gpl-howto.en.html.  If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by thegoodhen** [comment]
Thank you! I have to say this is my very first "serious" public project, and I am super new to all this, so I am glad you mentioned it. If you think it wouldn't trouble you too much to submit the PR, it would be awesome!

**Comment by thegoodhen** [comment]
Solved already thanks to f0x52 ! 
Thank you.
