### ISSUE TITLE
Shaky 3d objects despite good tracking

### ISSUE THREAD

**Issue by IanFLee** [thegoodhen/AprilTools#33]
I have been using April Tools with a fair amount of success. Recently I shot a video and tracked it. Admittedly the footage is shaky, but the grey marker covered the black tag perfectly all throughout, leading me to think that the tracking was just fine. However, another object in my scene (a Porsche) bounced around quite a lot. I'm not sure if this is an issue or some kind of user error. [Here is a youtube video of my attempt.](https://www.youtube.com/watch?v=TnzEOEHjhMk)

Any help would be much appreciated!

**Comment by BohdanOpyr** [comment]
The smaller your marker is, an the further you object from the marker, the harder it is to keep steady. That is because the tool can't tell where the marker is exactly (on the sub-pixel level), and even the most tiny error will be amplified with distance, producing these results.

**Comment by IanFLee** [comment]
Thanks!
