### ISSUE TITLE
april tools does not detect the contents of this folder

### ISSUE THREAD

**Issue by nonexistenttriangle** [thegoodhen/AprilTools#43]
april tools does not detect the contents of this folder.
solutions ive tried
-moving the images to a different folder
-changing the name of the folder the images are in
-splitting the source video into images again and using those instead
-using a different file extension (changing from .png to .jpg)
-restarting apriltools
no solution ive tried did anything

![image](https://user-images.githubusercontent.com/98267266/150681373-7e2430d1-e932-471d-bcbd-f780453dbefb.png)
![image](https://user-images.githubusercontent.com/98267266/150681390-df8e7e54-a44b-476a-b2b8-92a25c9d7112.png)

also important note: estimating focal length worked normally

**Comment by thegoodhen** [comment]
Interesting. That's just weird. Let me try to replicate the issue.

**Comment by thegoodhen** [comment]
Try:

apriltools.exe --path "C:/Users/Charlie/Videos/cuisine de la cuisine/New folder" --focal-length-pixels 1364.20 --tag-size 164.5

Closing the issue, feel free to open another one if the problem persists.
