### ISSUE TITLE
Issue when trying to import to blender

### ISSUE THREAD

**Issue by Greenvillman** [thegoodhen/AprilTools#47]
When i try to import the text file to blender (Blender 3.1)
It shows 3 errors 
Do i have to downgrade to lower versions like 2.8 its also fine by me
I even tried with the sample video and it didnt work either 
![image](https://user-images.githubusercontent.com/89898431/161438492-959327ec-1445-4ba9-9374-c08b960dbec8.png)
(the camera has no rotation or position by that i mean the rotation is 0,0,0 and position is 0,0,0 on all axis)

**Comment by thegoodhen** [comment]
Oh snap. I'll fix it tomorrow.

**Comment by Greenvillman** [comment]
Thanks

**Comment by thegoodhen** [comment]
Still on it, I planned to fix the import once export from the Python version works flawlessly, but I ran into issues while trying to get the Python version to work.

I'll probably skip the debugging of the Python and just hotfix the importer by itself.

**Comment by Greenvillman** [comment]
ok
take your time

**Comment by thegoodhen** [comment]
> ok take your time

I am unable to replicate the issue. Please, send me your track.txt data.

It works for me in Blender 3.0.1

I can try checking whether it works in your version of Blender. :)

**Comment by thegoodhen** [comment]
UGHHHH So it actually works in 3.0.1,
but is broken in 3.1.

I'll look into it, hold on.

**Comment by thegoodhen** [comment]
Okay, fixed it. Updating now.

**Comment by thegoodhen** [comment]
Fixed in the newest commit. Closing issue.
